<?php

namespace Suivi\SuiviBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OffresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffresRepository extends EntityRepository
{
}
