<?php

namespace Suivi\SuiviBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Vente1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Vente1Repository extends EntityRepository
{
}
