suivi_vente_categorie:
    resource: "@SuiviVenteBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie

suivi_vente_offres:
    resource: "@SuiviVenteBundle/Resources/config/routing/offres.yml"
    prefix:   /offres


suivi_vente_admin:
    path:     /admin
    defaults: { _controller: SuiviVenteBundle:Default:admin }
    
suivi_vente_chef:
    path:     /chef
    defaults: { _controller: SuiviVenteBundle:Default:chef }
    
suivi_vente_sup:
    path:     /sup
    defaults: { _controller: SuiviVenteBundle:Default:sup }
    

    
